[package]
name = "CoinSwap"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }
MoveNursery={local="../../../move/language/move-stdlib/nursery/"}
BaseCoin={local="../BaseCoin"}

[addresses]
std =  "0x1"
dev = "0x2"
module_owner = "0x06"


